/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Plants: (() => {
      const tableId = new TableId("", "Plants");
      return defineComponent(
        world,
        {
          chainId: RecsType.Number,
          contractAddress: RecsType.String,
          tokenId: RecsType.BigInt,
          grower: RecsType.String,
          plot: RecsType.Number,
          plantedAt: RecsType.BigInt,
          wateredAt: RecsType.BigInt,
          entropy: RecsType.BigInt,
          lifecycleStage: RecsType.Number,
          ipfsHash: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Projects: (() => {
      const tableId = new TableId("", "Projects");
      return defineComponent(
        world,
        {
          growthCycleBlocks: RecsType.BigInt,
          lifecycleLength: RecsType.Number,
          name: RecsType.String,
          ipfsHash: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
