// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Plants, PlantsData, PlantsTableId } from "./tables/Plants.sol";
import { Projects, ProjectsData, ProjectsTableId } from "./tables/Projects.sol";
