// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum PlantLifecycleStage {
  SEED,
  SEEDLING,
  BUD,
  COMMON_FLOWER,
  UNCOMMON_FLOWER,
  RARE_FLOWER,
  LEGENDARY_FLOWER
}
