// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IProjectSystem {
  function integrateProject(uint16 chainId, address contract_, string calldata name) external;
}
